# Use root/example as user/password credentials
version: '3.1'

services:
  api-service:
    image: golang-rest-api:latest
    restart: always
    ports:
      - 9000:8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projectmanager
